### ISSUE TITLE
Only some of Undead herald's trades are displaying

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#14]
When I printed out the usages for Silver coin, it did printout all trades with the exception of Undead herald. Only 4 of his trades are there.
![image](https://user-images.githubusercontent.com/38159897/122499077-17c0d900-cfa5-11eb-8ef3-9a77fe1f6e17.png)

**Comment by Tslat** [comment]
This one could be interesting
It' sbecause undead herald does trades in a bit of a special way.. not sure how to get them to be included
