### ISSUE TITLE
Item loot tables use similar formatting to entity tables, when they shouldn't?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#18]
Items like Shiny box and treasure box aren't affected by looting, shouldn't item loot tables use a similar format to structure loot chest tables?
![image](https://user-images.githubusercontent.com/38159897/123362149-13586b00-d525-11eb-938b-cf2eb91a642f.png)

**Comment by Tslat** [comment]
This is the wiki template's fault, not the mod
