### ISSUE TITLE
Add the ability to print new tables for config options

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#3]
![image](https://user-images.githubusercontent.com/44556728/81133982-4571cc80-8f21-11ea-8533-e41c8c738822.png)
![image](https://user-images.githubusercontent.com/44556728/81134052-7520d480-8f21-11ea-851d-fd838b0bcc23.png)
![image](https://user-images.githubusercontent.com/44556728/81134076-8e298580-8f21-11ea-8d9e-65e696e5b41a.png)

This is a copy of the request I made on Discord. 

Here is the raw paste for the tables:

Structures:
>{| class = "wikitable"
|-
! Structure !! Default value !! Description
|-
| [[Abyssal Lotto Hut]] || 440 || description (will be inputed manually)
|-
|}

Ores:
>=== [[Amethyst Ore]] ===
{| class = "wikitable"
|-
! Config option !! Allowed values !! Default value !! Description
|-
| I:maxOresPerVein | | Any number between 1 and 30 (inclusive) || 9||description (will be inputed manually)
|-
| I:maxOresPerChunk | | Any number between 0 and 20 (inclusive) || 5|| description (will be inputed manually)
|-
| I:minOresPerVein | | Any number between 1 and 20 (inclusive) || 5|| description (will be inputed manually)
|-
|}

Hunter mobs:

> {| class = "wikitable"
|-
! Mob  !! Mob id !! Default level !! Default xp
|-
| [[Anemia]] | | aoa3:anemia || 1 || 23.1
|-
|}

As stated, this is going to be used on the Configuration page. Note that the discord text had weird formatting with the || which I fixed here.

**Comment by Tslat** [comment]
Done in 1.8
