### ISSUE TITLE
Remove the first link on the Smoker and Campfire sentences.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#31]
The wikihelper printouts for smokers and campfires pastes a link in the first word of the sentence. For example, if I type
/wikihelper recipe aoa3:campfire_cooked_fish_from_turquoise_stripefish, it will print: 

[[Turquoise Stripefish (Item)|Turquoise Stripefish (Item)s]] can be cooked on a [[Campfire]] to produce 1 [[Cooked Fish]] and 3xp, taking 30 seconds.

The [[Turquoise Stripefish (Item)|Turquoise Stripefish (Item)s]] link is unnecessary as the above sentence should only ever be posted on the same page it links to.

**Comment by EatingSilencer** [comment]
I will also note that if you do do this suggestion, make sure the first word isn't printing with a suffix.

**Comment by Tslat** [comment]
It's done like that to be page-agnostic so it can be used anywhere

The wiki automatically strips links that are self-directing anyway so it shouldn't be an issue

**Comment by EatingSilencer** [comment]
> The wiki automatically strips links that are self-directing anyway so it shouldn't be an issue

The wiki turns them into bolded text, which looks awkward in some contexts that its used in. So in a way it very well could be an issue.
