### ISSUE TITLE
Hauling table does not take images into account

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#32]
2.5.1

The /wikihelper haulingtable command takes mob names into account for links but does not take them into account for the images. To fix this, an image: parameter needs to be added to the rows per loot table, e.g.: image: Chocaw (entity).png.

**Comment by Tslat** [comment]
The loot table template handles this on its own - or it should when it gets updated
Same as it does for non-entity entries

**Comment by EatingSilencer** [comment]
Sigh, you're right. I feel dumb.

**Comment by EatingSilencer** [comment]
Sigh, you're right. I don't know how I didn't manage to notice that.
