### ISSUE TITLE
Generate infoboxes command (PR Suggestion for contributors)

### ISSUE THREAD

**Issue by Tslat** [Tslat/AoAWikiHelperMod#33]
A command to generate the wiki template text for infoboxes & their content (item, block, entity, etc.)

Command structure might look like this:

`/wikihelper infobox <item|block|entity|structure|etc> <id>`

**Comment by c64cosmin** [comment]
Block is done because it worked for 
`/wikihelper infobox <block id>`
not it works like
`/wikihelper infobox block <block id>`
Also item work using
`/wikihelper infobox item <item id>`

**Comment by c64cosmin** [comment]
Items are done and broken into following categories:
blaster,bow,cannon,crossbow,greatblade,gun,maul,shotgun,sniper,staff,sword,thrown,vulcane
