### ISSUE TITLE
Add a functionality to print structure data into table format

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#4]
On the Structures page on the wiki, I would like to create a table listing all structures that can be generated by the /aoastructure command. This is a tedious process to do by hand as there are a lot of them, so I am suggesting to add this functionality to the aoawikihelper mod to help out with this.

I would like the wiki helper mod to generate a table like this:

{| class = "wikitable"
|-
! Image !! Name !! {{tooltip|ID|The ID used to spawn the structure with commands.}} || Location 
|-
| [[File:Abyssal Lotto Hut.png|300px]] || [[Abyssal Lotto Hut]] || '''AbyssalLottoHut''' || Generates on the surface of [[the Abyss]]. 
|- 
|}

It would have a row for each structure. The first column would have a picture of the structure with the same name as the structure. The second would be the structure's name, and the third would be the structure's id. The fourth and fifth columns would be manually inputted.

I'm not sure how hard it would be to generate the structure name (maybe by taking the id and splitting it apart based on where the capital letters are). If you can't do this, I guess just list the id for the name and I'll go through them manually.

**Comment by Tslat** [comment]
Done in next version
