### ISSUE TITLE
Wikihelper placing "(item)" on certain items

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#42]
This includes items with an entity version of themselves, or items that share a name with a projectile like Hot shot. This causes labelling problems like this
![image](https://user-images.githubusercontent.com/38159897/164524323-12009874-958b-4436-aa6a-976b6984b0e7.png)

**Comment by Tslat** [comment]
This is a result of the change silencer wanted when items have ids that match entities

**Comment by Cruuk** [comment]
Solution from discord
![image](https://user-images.githubusercontent.com/38159897/164547737-199f6ab1-5a61-45a3-bc3f-51fa8ec68df2.png)
