### ISSUE TITLE
Wikihelper labelling vanilla items with a weird Forge tag thing

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#43]
Mainly applies to the crafting/infusing function. Certain vanilla items get printed out looking like this
![image](https://user-images.githubusercontent.com/38159897/164525595-c31025c0-f343-43bf-9403-c0372eff7aee.png)

When they should look like this
![image](https://user-images.githubusercontent.com/38159897/164525738-0925e6dd-10d1-4a3b-b5ab-79495bf4d6b9.png)

**Comment by Tslat** [comment]
Yeah they're called tags

**Comment by Cruuk** [comment]
![image](https://user-images.githubusercontent.com/38159897/164578719-eb248133-3e39-4f6e-85f9-54ff4eef97e2.png)

**Comment by Cruuk** [comment]
![image](https://user-images.githubusercontent.com/38159897/164579463-59a380ba-4297-4d77-82b6-4fbe934d052b.png)
Also
