### ISSUE TITLE
New revised table for the Infusion page

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#5]
The table as currently mostly set up on the Infusion page that lists the enchantments is somewhat inaccurate: it lists one recipe for each enchantment even though more than one exists.

Here is a new table idea. I think for the sake of making it easier to print: just generate the following table with all of the imbuing recipes that exist (since they should all be enchantments anyway):

> {| class = "wikitable"
> |-
> ! Enchantment !! Applicable to !! Level req !! Recipe
> |-
> | '''[[Archmage I]]''' || Staves || 70 || {{Infusion
> |a1=Durability Enhancer
> |a1image=Durability Enhancer.png
> |a2=Magic Enhancer
> |a2image=Magic Enhancer.png
> |a3=Radiant Power Stone
> |a3image=Radiant Power Stone.png
> |output=Air
> |outputimage=Air.png
> |inputimage=Air.png
> |input=Air
> |amount=0
> |shapeless=1
> }}
> |-
> | '''[[Archmage II]]''' || Staves || 80 || {{Infusion
> |a1=Durability Enhancer
> |a1image=Durability Enhancer.png
> |a2=Magic Enhancer
> |a2image=Magic Enhancer.png
> |a3=Magic Enhancer
> |a3image=Magic Enhancer.png
> |b1=Blooming Power Stone
> |b1image=Blooming Power Stone.png
> |output=Air
> |outputimage=Air.png
> |inputimage=Air.png
> |input=Air
> |amount=0
> |shapeless=1
> }}
> |-
> |}

**Comment by EatingSilencer** [comment]
The code doesn't seem to want to format correctly...

**Comment by Tslat** [comment]
I'm not sure this is going to be very viable, it's going to cause rows to become huge because of the number of recipes in there.

**Comment by EatingSilencer** [comment]
What do you mean? All of the recipes aren't going to be kept in a megatable, I was going to split it up into separate tables for each enchantment.

**Comment by Tslat** [comment]
So what you actually want is a way to print out the recipes for a given enchantment then

**Comment by EatingSilencer** [comment]
Sure, but in table format, like listed in the OP. Individual prints for each recipe or all recipes for an enchantment.
