### ISSUE TITLE
Block loot tables not printing at all

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#51]
Using wikihelper 2.9.3.3.

When trying to run /wikihelper loottable block ... it does not print the block's loot table properly. Instead it just prints this:
![image](https://user-images.githubusercontent.com/44556728/167324608-214a8051-3527-4cf2-afb2-37968d4bf929.png)

**Comment by Tslat** [comment]
Unable to replicate
