### ISSUE TITLE
Stonecutting printouts are broken

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/AoAWikiHelperMod#59]
The table template is left out, leaving only the items used.

**Comment by Tslat** [comment]
Got an example of what it should look like?

**Comment by EatingSilencer** [comment]
`{| class = "wikitable"`
`|-`
`! Block !! Ingredients !! Item`
`|-`
`|[[File:Stonecutter.png|32px|link=]] [[Stonecutter]] || [[File:Fungal Rock.png|32px|link=]] Fungal Rock || [[File:Fungal Rock Slab.png|32px|link=]] 2 [[Fungal Rock Slab]]s`
`|-`
`|[[File:Stonecutter.png|32px|link=]] [[Stonecutter]]||[[File:Fungal Rock.png|32px|link=]] Fungal Rock||[[File:Fungal Rock Stairs.png|32px|link=]] [[Fungal Rock Stairs]]`
`|-`
`|[[File:Stonecutter.png|32px|link=]] [[Stonecutter]]||[[File:Fungal Rock.png|32px|link=]] Fungal Rock||[[File:Fungal Rock Wall.png|32px|link=]] [[Fungal Rock Wall]]`
`|-`
`|}`
