### ISSUE TITLE
Infusion table doesn't like tags in the input slot

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#68]
The template for the input slot of Infusion table does not appear to support tags
![image](https://user-images.githubusercontent.com/38159897/180097560-710e4048-c78e-403f-9a65-c1be59c5baa2.png)

**Comment by Tslat** [comment]
Is this a wiki issue or a wikihelper issue?

**Comment by Cruuk** [comment]
Uhh I don't know, I assume it would be a wikihelper problem. It shouldn't be any different from any other crafting slot

It should be <code>{{tooltip|forge:rods/metal|Any item tagged as forge:rods/metal}} ([[Tags#minecraft:item:forge:rods/metal|Tag]])</code>

But in this instance, it just prints out <code>[[forge:rods/metal]]</code> and nothing else. Unsure what would cause it to do that
![image](https://user-images.githubusercontent.com/38159897/180144809-5471b837-e23f-4b88-acb1-004c554d5e21.png)
