### ISSUE TITLE
Iso command spams errors in console when printing iso for Nethengic Beast

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/AoAWikiHelperMod#73]
Using 2.9.16 (reupload)

When running the command /wikihelper iso entity aoa3:nethengeic_beast, it spams errors in the console, as shown in the below picture. Funnily enough, the isometric for nethengeic beast is still made and it appears to be perfectly fine.
![image](https://user-images.githubusercontent.com/44556728/208714954-29b0ea83-bf84-4cfc-ad70-2327c0acdeb5.png)

**Comment by Tslat** [comment]
> p
