### ISSUE TITLE
Issue with generating armor stands wearing armor?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#78]
The NBT doesn't work even though it works when used in a /summon command

**Comment by Tslat** [comment]
Works fine for me?

/wikihelper iso entity minecraft:armor_stand {ArmorItems: [{id:"aoa3:ice_boots", Count: 1b}, {id:"aoa3:ice_leggings", Count: 1b}, {id:"aoa3:ice_chestplate", Count: 1b}, {id:"aoa3:ice_helmet", Count: 1b}], Invisible: 1b}
